version: '2'

services:
   minecraft:
      image: drunner/minecraft
      volumes:
         - "config:/config"
         - "data:/minecraft/data"
      ports:
         - "${PORT}:25565"
         - "${PORT}:25565/udp"
      restart: always
      command: /usr/local/bin/runminecraft.sh
      network_mode: "bridge"

volumes:
   config:
      external:
         name: "drunner-${SERVICENAME}-config"

   data:
      external:
         name: "drunner-${SERVICENAME}-minecraftdata"

# required to use save_environment, allowing us to define
# configuration that dRunner puts in the environment when
# servicerunner is called. We use it for the PORT.
   env:
      external:
         name: "${SERVICENAME}-environment"
