version: '2'

services:
   minecraft:
      image: drunner/minecraft
      volumes:
         - "data:/minecraft/data"
      ports:
         - "${PORT}:25565"
         - "${PORT}:25565/udp"
      restart: always
      command: /usr/local/bin/runminecraft.sh
      network_mode: "bridge"

volumes:
   data:
      external:
         name: "drunner-${SERVICENAME}-minecraftdata"
