version: '2'

services:
   minecraft:
      image: drunner/minecraft
      volumes:
         - "drunner-data:/minecraft/data"
      ports:
         - "${PORT}:25565"
         - "${PORT}:25565/udp"
      restart: always
      command: /usr/local/bin/runminecraft.sh
      network_mode: "bridge"

volumes:
   # the compose label for the volume contains 'drunner' so that it's managed by drunner.
   drunner-data:
      external:
         # this is the actual volume name. Include ${SERVICENAME} to disambiguate multiple installs.
         name: "drunner-${SERVICENAME}-minecraftdata"
