# drunner service configuration for helloworld
#
---
configuration:
   PORT:
      description: "The port to run minecraft on."
      default: 25565
      type: port

volumes:
   drunner-${SERVICENAME}-minecraftdata:
      backup: true

containers:
   - drunner/minecraft

commands:
   _stop:
      - dstop drunner-${SERVICENAME}-minecraft

   stop:
      - _stop

   start:
      - docker run -d
         -p ${PORT}:25565 -p ${PORT}:25565/udp
         -v drunner-${SERVICENAME}-minecraftdata:/minecraft/data
         --restart=always
         --name drunner-${SERVICENAME}-minecraft
         /usr/local/bin/runminecraft.sh

#
# - HOOKS -
   obliterate_start:
      - _stop
   uninstall_start:
      - _stop
   backup_start:
      - docker pause drunner-${SERVICENAME}-minecraft
   backup_end:
      - docker resume drunner-${SERVICENAME}-minecraft

help: |
   NAME
      ${SERVICENAME} - Runs minecraft

   SYNOPSIS
      ${SERVICENAME} help             - This help
      ${SERVICENAME} configure [PORT] - Show configuration, or set PORT
      ${SERVICENAME} start            - Make it go!
      ${SERVICENAME} stop             - Stop it

   DESCRIPTION
      Built from ${IMAGENAME}.
